name: animation_samples
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  fluttericon: ^2.0.0
  google_fonts: ^5.1.0
  ui_common:
    git: https://github.com/brocodev/ui_common.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/img/samples/
  - assets/img/vice/
  - assets/images/
